version: '3.8'

services:

  network-creator:
    image: alpine:latest
    command: echo "Red creada"
    networks:
      - microservices-network

networks:
  microservices-network:
    driver: bridge