# Orquestación completa para desarrollo
version: '3.8'

services:
  # Servicios compartidos
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    networks:
      - microservices-network

  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: microtask_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - microservices-network

  # Microservicios
  api-gateway:
    build:
      context: .
      dockerfile: apps/api-gateway/Dockerfile
    container_name: api-gateway
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
    volumes:
      - ./apps/api-gateway/src:/app/apps/api-gateway/src
      - ./node_modules:/app/node_modules
    networks:
      - microservices-network
    depends_on:
      - postgres
      - rabbitmq

  auth-microservice:
    build:
      context: .
      dockerfile: apps/auth-microservice/Dockerfile
    container_name: auth-microservice
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - PORT=3001
    volumes:
      - ./apps/auth-microservice/src:/app/apps/auth-microservice/src
      - ./node_modules:/app/node_modules
    networks:
      - microservices-network
    depends_on:
      - postgres
      - rabbitmq

  microtask-manager:
    build:
      context: .
      dockerfile: apps/microtask-manager/Dockerfile
    container_name: microtask-manager
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=development
      - PORT=3002
    volumes:
      - ./apps/microtask-manager/src:/app/apps/microtask-manager/src
      - ./node_modules:/app/node_modules
    networks:
      - microservices-network
    depends_on:
      - postgres
      - rabbitmq

volumes:
  postgres_data:

networks:
  microservices-network:
    driver: bridge