# Servicios compartidos (solo message broker)
version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"   # Puerto AMQP para microservicios
      - "15672:15672" # Puerto web UI (admin:admin)
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - microservices-network
    restart: unless-stopped

volumes:
  rabbitmq_data:

networks:
  microservices-network:
    driver: bridge