version: '3.8'

services:
  task-postgres:
    image: postgres:13
    container_name: task-postgres
    environment:
      POSTGRES_USER: task_user
      POSTGRES_PASSWORD: task_password
      POSTGRES_DB: task_db
    ports:
      - "5434:5432"
    volumes:
      - task_postgres_data:/var/lib/postgresql/data
    networks:
      - microservices-network
    restart: unless-stopped

  mongo:
    image: mongo
    container_name: task-mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27018:27017"
    networks:
      - microservices-network
  task-microservice:
    build:
      context: ../../
      dockerfile: apps/task-microservice/Dockerfile
    container_name: task-microservice
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=development
      - PORT=3002
      - POSTGRES_HOST=task-postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=task_user
      - POSTGRES_PASSWORD=task_password
      - POSTGRES_DB=task_db
      - RABBITMQ_URL=amqp://user:password@rabbitmq:5672
      - JWT_SECRET=super-secret-jwt-key-here
    volumes:
      - ../../apps/task-microservice/src:/app/apps/task-microservice/src
      - ../../node_modules:/app/node_modules
    networks:
      - microservices-network
    depends_on:
      - task-postgres
    restart: unless-stopped

volumes:
  task_postgres_data:

networks:
  microservices-network:
    external: true